### ISSUE TITLE
Error loading The Outsider DLC Save

### ISSUE THREAD

**Issue by SPKuja** [apocalyptech/swh_savegame#1]
Hi, I don't know if this is monitored anymore (great work on the editor!) but if trying to load an Outside DLC save, I get the below error:

> C:\PATH\TO\EDITOR>swh_savegame.py savegame_000.dat -c
Traceback (most recent call last):
  File "C:\PATH\TO\EDITOR\swh_savegame.py", line 1149, in <module>
    sg.load(args.input[0])
  File "C:\PATH\TO\EDITOR\swh_savegame.py", line 793, in load
    assert self.unknown_23 == 0
AssertionError

Granted, this is a Vita save - but it worked flawlessly prior to purchasing the DLC.

**Comment by apocalyptech** [comment]
Huh, interesting.  Could you attach the savegame?  I'd tested this out primarily on Outsider DLC; it's possible that the Vita is storing those differently.  Or just the editor is being too picky about the file.

**Comment by SPKuja** [comment]
Sure thing. I tried with multiple flags as well - even the --check flag threw up an area. Thanks for taking a look!
[savegame_000.zip](https://github.com/apocalyptech/swh_savegame/files/3327513/savegame_000.zip)

**Comment by apocalyptech** [comment]
Hello!  Just pushed a change which should fix this for you.  Did you happen to have any earlier savegame backups available still, btw?  The change I made works on all the saved games that I still have, but it'd be nice to have a few data points.  No worries if not, of course!

Regardless, grab the newer files, it should fix it up for you.  Enjoy!

**Comment by SPKuja** [comment]
Works perfectly, thank you! I believe the save attached is a pre-Outsider DLC save. I hope it helps!
[savegame_000.zip](https://github.com/apocalyptech/swh_savegame/files/3328833/savegame_000.zip)

**Comment by apocalyptech** [comment]
Awesome, glad it's working.  Thanks for the extra save!
